# Site settings
title: Siwan's blog
email: 21900429@handong.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/Yangsiwan/Yangsiwan.github.io" # the base hostname & protocol for your site
twitter_username: siwan
github_username:  Yangsiwan

# Build settings
markdown: kramdown
